INSERT INTO BOOK (BOOK_NAME, STREAM, AUTHOR, PUBLISHER, YEAR_OF_PUBLICATION) VALUES ('book1', 'Engg', 'author1', 'publisher1', 2001);
INSERT INTO BOOK (BOOK_NAME, STREAM, AUTHOR, PUBLISHER, YEAR_OF_PUBLICATION) VALUES ('book2', 'Engg', 'author1', 'publisher1', 2002);
INSERT INTO BOOK (BOOK_NAME, STREAM, AUTHOR, PUBLISHER, YEAR_OF_PUBLICATION) VALUES ('book3', 'Med', 'author1', 'publisher1', 2002);
INSERT INTO BOOK (BOOK_NAME, STREAM, AUTHOR, PUBLISHER, YEAR_OF_PUBLICATION) VALUES ('book4', 'Med', 'author1', 'publisher1', 2004);